# Generated by Django 5.2.7 on 2025-10-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_alter_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='color',
        ),
    ]
