# Generated by Django 5.2.7 on 2025-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_icon_unit_category_icon_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
